Controllers/tool_typeController.cs
using hrm.Database;
using hrm.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;

namespace hrm.Controllers
{
    [AuthorizeVerifiedloggedin]
    public class tool_typeController : Controller
    {
        public List<int> _permission;
        public tool_typeController()
        {
            string PList = System.Web.HttpContext.Current.Request.Cookies["_plist"] == null ? "0" : System.Web.HttpContext.Current.Request.Cookies["_plist"].Value.ToString();
            _permission = PList == "0" ? null : JsonConvert.DeserializeObject<List<int>>(PList);
        }
        public ActionResult Index()
        {
            if (!_permission.Contains(5077))
            {
                return View("unauth");
            }
            int workspaceid = Convert.ToInt32(Request.Cookies["domain"].Value.ToString());
            tooltype _model = new tooltype();
            var toolservices = new toolservices();
            _model.tool_type = toolservices.GetAllActiveToolType(workspaceid);
            _model.mainorder = _model.tool_type.Count>0? _model.tool_type.Max(a=>a.mainorder)+1:1;
            string message = TempData["error"] != null? TempData["error"].ToString():string.Empty; 
           _model.PERMISSIONS = _permission;
            _model = new helper().GenerateError<tooltype>(_model, message);
            return View(_model);
        }


        [HttpPost]
        public ActionResult Index(tooltype _model)
        {
            int workspaceid = Convert.ToInt32(Request.Cookies["domain"].Value.ToString());
            var toolservices = new toolservices();
            int userid = Convert.ToInt32(Request.Cookies["_xid"].Value.ToString()); 
            var error_text = toolservices.AddNewToolType(_model.name, userid,_model.mainorder, workspaceid); 
            tooltype _model1 = new tooltype();
            if (!error_text.ToLower().Contains("error"))
            {
                ModelState.Clear();
            }
            _model1.tool_type = toolservices.GetAllActiveToolType(workspaceid);
            _model1.mainorder = _model1.tool_type.Count > 0 ? _model1.tool_type.Max(a => a.mainorder) + 1 : 1;
            _model1 = new helper().GenerateError<tooltype>(_model1, error_text);
            _model1.PERMISSIONS = _permission;
            return View(_model1);
        }

        [HttpPost]
        public ActionResult update(string name, int id,int mainorder)
        {
            int workspaceid = Convert.ToInt32(Request.Cookies["domain"].Value.ToString());
            var toolservices = new toolservices();
            int userid = Convert.ToInt32(Request.Cookies["_xid"].Value.ToString()); 
            var error_text = toolservices.UpdateToolType(name, id, userid, mainorder);
            tooltype _model = new tooltype();
            ModelState.Clear();
            _model.tool_type = toolservices.GetAllActiveToolType(workspaceid);
            _model.mainorder = _model.tool_type.Count > 0 ? _model.tool_type.Max(a => a.mainorder) + 1 : 1; 
            _model = new helper().GenerateError<tooltype>(_model, error_text);
            _model.PERMISSIONS = _permission;
            return View("index", _model);
        }
        public ActionResult delete(int id)
        {
            if (!_permission.Contains(5112))
            {
                return View("unauth");
            }
            int workspaceid = Convert.ToInt32(Request.Cookies["domain"].Value.ToString());
            var toolservices = new toolservices();
            int userid = Convert.ToInt32(Request.Cookies["_xid"].Value.ToString()); 
            var error_text = toolservices.DeleteToolsType(id, userid);
            tooltype _model = new tooltype(); ModelState.Clear();
            _model.tool_type = toolservices.GetAllActiveToolType(workspaceid);
            _model.mainorder = _model.tool_type.Count > 0 ? _model.tool_type.Max(a => a.mainorder) + 1 : 1;
            _model = new helper().GenerateError<tooltype>(_model, error_text);
            _model.PERMISSIONS = _permission;
            return View("index", _model);
        }


    }
}

Views/tool_type/Index.cshtml
@{
    ViewBag.Title = "Tool Type";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int _count = 0;
}
@model hrm.Models.tooltype
<div class="p-10">
</div>
<div class="p-30 p-t-none p-b-none">
    @if (!string.IsNullOrEmpty(Model.error_text))
    {
        <span id="alert" style="display:none;" data-class="@Model.alertclass" data-text="@Model.error_text"></span>
    }
    <div id="mdlupdate" class="modal fade" data-backdrop="static" data-keyboard="false" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                    <h4 class="modal-title" id="myModalLabel">Edit Tool Type</h4>
                </div>
                @using (Html.BeginForm("update", "tool_type", FormMethod.Post, new { @id = "frmsendsms" }))
                {<div class="modal-body">
                        <div class="form-group">
                            <label>Type </label>
                            <input type="text" class="form-control" required="" id="deptname" name="name">
                            <input type="hidden" name="id" id="deptid" />
                        </div>
                        <div class="form-group">
                            <label>View order </label>
                            <input type="text" class="form-control" required="" id="mainorderid" name="mainorder">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-success"><i class="fa fa-save"></i> Update</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fas fa-times-circle"></i> Close</button>
                    </div>
                }
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4">
            <div class="panel">
                <div class="panel-body">
                    @using (Html.BeginForm("index", "tool_type", FormMethod.Post, new { @id = "ToolTypeAdd" }))
                    {
                        <div class="panel-heading">
                            <h3 class="panel-title pd-0"> Create Tool Type</h3>
                        </div>
                        <div class="form-group">
                            <label>Type</label>
                            @Html.TextBoxFor(a => a.name, new { @class = "form-control" })
                            @Html.ValidationMessageFor(a => a.name)
                        </div>
                        <div class="form-group">
                            <label>View order</label>
                            @Html.TextBoxFor(a => a.mainorder, new { @class = "form-control" })
                        </div>
                        <button type="button" onclick="AddToolType('@Model.PERMISSIONS.Contains(5114).ToString()','You are not authorized to add new tool type')" class="btn btn-success btn-sm pull-right"><i class="fa fa-save"></i> Save </button>
                    }
                </div>
            </div>
        </div>
        <div class="col-lg-8">
            <div class="panel">
                <div class="panel-heading pd-12">
                    <h3 class="panel-title">
                        Tool Type
                    </h3>
                </div>
                <div class="panel-body p-none">
                    <div class="row">
                        <div class="col-sm-12">
                            <table class="table data-table nowrap table-hover table-ultra-responsive dataTable no-footer" id="table">
                                <thead>
                                    <tr>
                                        <th>No.</th>
                                        <th>Type</th>
                                        <th>View Order</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.tool_type)
                                    {
                                        _count = _count + 1;
                                        <tr role="row" class="odd">
                                            <td>@_count</td>
                                            <td>
                                                @if (Model.PERMISSIONS.Contains(5111))
                                                {
                                                    <a href="#" onclick="update('@item.typeid','@item.name','@item.mainorder')">@item.name</a>
                                                }
                                                else
                                                {
                                                    <a href="#" class="disabledbtn" data-msg="You are not authorized to edit selected type">@item.name</a>

                                                }
                                            </td>
                                            <td>@item.mainorder</td>
                                            <td>
                                                <div class="btn-group pos-static">
                                                    <a class="customedropdown" data-toggle="customedropdown" aria-haspopup="true" aria-expanded="false">
                                                        <i class="fa fa-ellipsis-v fn21"></i>
                                                    </a>
                                                    <div class="dropdown-menu customdropdown-menu" x-placement="bottom-start" style="top: 0px; transform: translate3d(-38px, 10px, 0px); will-change: transform; position: absolute; left: 0px; display: none;">

                                                        @if (Model.PERMISSIONS.Contains(5111))
                                                        {
                                                            <a class="btn btn-success btn-xs" onclick="update('@item.typeid','@item.name','@item.mainorder')"><i class="fa fa-edit"></i> Edit</a>
                                                        }
                                                        else
                                                        {
                                                            <a href="#" class="btn btn-success btn-xs disabledbtn" data-msg="You are not authorized to edit selected type"><i class="fa fa-edit"></i> Edit</a>
                                                        }
                                                        @if (Model.PERMISSIONS.Contains(5112))
                                                        {
                                                            <a href="#" class="btn btn-danger btn-xs cdelete" id="@item.typeid"><i class="fa fa-trash"></i> Delete</a>
                                                        }
                                                        else
                                                        {
                                                            <a href="#" class="btn btn-danger btn-xs disabledbtn" data-msg="You are not authorized to delete selected type"><i class="fa fa-trash"></i> Delete</a>
                                                        }
                                                        <a class="btn btn-info btn-xs"><i class="fa fa-window-close"></i> Close</a>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    } 
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div> 
    </div> 
</div>
<script>
    $(document).ready(function () {
        $('.data-table').DataTable({ "bSort": false, "pageLength": 25 ,"oLanguage": { "sSearch": "", 'sLengthMenu': "Show _MENU_" }}); 
        $(".cdelete").on("click", function (e) {
            e.preventDefault();
            var id = this.id;
            bootbox.confirm("Are you sure?", function (result) {
                if (result) {
                    var _url = "/tool_type/delete";
                    window.location.href = _url + "?id=" + id;
                }
            });
        });
    });
    function update(deptid, deptname, mainorderid) {
        $('#mdlupdate').modal('show');
        $("#deptname").val(deptname);
        $("#deptid").val(deptid);
        $("#mainorderid").val(mainorderid);
    }
    function Uploadfile() {
        $('#upload').modal('show');
    } 

    function AddToolType(Permissions, Message) {
        if (Permissions == 'True') {
            $("#ToolTypeAdd").submit();
        } else {
            alertify.log(Message, 'error', 5000);
            setTimeout(function () {
                $("#alert").hide();
            }, 5000);
        }
        
    }
</script>