Controllers/partnersController.cs
using hrm.Database;
using hrm.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
namespace hrm.Controllers
{

    [AuthorizeVerifiedloggedin]
    public class partnersController : Controller
    {
        public List<int> _permission;
        public partnersController()
        {
            string PList = System.Web.HttpContext.Current.Request.Cookies["_plist"] == null ? "0" : System.Web.HttpContext.Current.Request.Cookies["_plist"].Value.ToString();
            _permission = PList == "0" ? null : JsonConvert.DeserializeObject<List<int>>(PList);
        }
        public string get_client_rate(int id)
        { 
            return new clientservices().GetClientRate(id);
        } 
        public ActionResult Index()
        {
            if (!_permission.Contains(5103))
            {
                return View("unauth");
            } 
            partnermodal _model = new partnermodal();
            _model.PERMISSIONS = _permission;
            if (TempData["error"] != null)
            { 
                _model = new helper().GenerateError<partnermodal>(_model, TempData["error"].ToString());
            }
            return View(_model);
        }
        public JsonResult Fetchpartners(int start = 0, int length = 25, int draw = 1)
        {
            int workspaceid = Convert.ToInt32(Request.Cookies["domain"].Value.ToString());
            string search = Request.Params["search[value]"] ?? "";
            start = start == 0 ? 1 : start + 1;
            length = start == 1 ? length : start - 1 + length;
            partnerService _services = new partnerService();
            datatableAjax<partnermodal_item> tableDate = new datatableAjax<partnermodal_item>();
            int total = 0;
            var _model = _services.get_all_active_partners_bypaging(ref total, start, length, search, workspaceid);
            tableDate.draw = draw;
            tableDate.data = _model;
            tableDate.recordsFiltered = _model.Count() > 0 ? total : 0;
            tableDate.recordsTotal = total;
            return base.Json(tableDate, JsonRequestBehavior.AllowGet);
        }
        public JsonResult Fetchmanagers(int start = 0, int length = 25, int draw = 1, int partnerid = 0)
        {
            int workspaceid = Convert.ToInt32(Request.Cookies["domain"].Value.ToString());
            string search = Request.Params["search[value]"] ?? "";
            start = start == 0 ? 1 : start + 1;
            length = start == 1 ? length : start - 1 + length;
            prjmanagerservices _services = new prjmanagerservices();
            datatableAjax<prjmngr_item> tableDate = new datatableAjax<prjmngr_item>();
            int total = 0;
            var _model = _services.get_all_active_prj_bypartner_byindex(ref total, partnerid, start, length, search, workspaceid);
            tableDate.draw = draw;
            tableDate.data = _model;
            tableDate.recordsFiltered = _model.Count() > 0 ? total : 0;
            tableDate.recordsTotal = total;
            return base.Json(tableDate, JsonRequestBehavior.AllowGet);
        }
        public ActionResult add()
        {
            if (!_permission.Contains(5095))
            {
                return View("unauth");
            }
            partnermodal_item _item = new partnermodal_item();
            return View(_item);
        }
        [HttpPost]
        public ActionResult add(partnermodal_item _item)
        {
            int workspaceid = Convert.ToInt32(Request.Cookies["domain"].Value.ToString());
              int userid = Convert.ToInt32(Request.Cookies["_xid"].Value.ToString());
            partnermodal _model = new partnermodal();
            partnerService _services = new partnerService();
            _model.PERMISSIONS = _permission;
            var message = _services.add_new_partner(_item, userid, workspaceid);
            _model = new helper().GenerateError<partnermodal>(_model, message);
            return View("Index", _model);
        }
        public ActionResult delete(string token)
        {
            if (!_permission.Contains(5098))
            {
                return View("unauth");
            }
            int id = Convert.ToInt32(new Crypto().DecryptStringAES(token));
               partnermodal _model = new partnermodal();
            partnerService _services = new partnerService();
            var message = _services.delete_partner(id);
            _model.PERMISSIONS = _permission;
            _model = new helper().GenerateError<partnermodal>(_model, message);
            return View("Index", _model);
        }
        public ActionResult edit(string token)
        {
            if (!_permission.Contains(5096))
            {
                return View("unauth");
            }
            int id = Convert.ToInt32(new Crypto().DecryptStringAES(token));
            partnerService _services = new partnerService(); 
            partnermodal_item _item = _services.get_all_active_partners_byid(id); 
            return View(_item);
        }
        public ActionResult view(string token)
        {
            if (!_permission.Contains(5097))
            {
                return View("unauth");
            }
            int id = Convert.ToInt32(new Crypto().DecryptStringAES(token));
               partnerviewmodal _model = new partnerviewmodal();
            partnerService _services = new partnerService();
            if (TempData["error"] != null)
            { 
                _model = new helper().GenerateError<partnerviewmodal>(_model, TempData["error"].ToString());
            }
            _model.PERMISSIONS = _permission;
            _model.partnerid = id;
            _model.partners = _services.get_all_active_partners_byid(id); 
            return View(_model);
        }
        [HttpPost]
        public ActionResult add_manager(prjmngr_item prjectmgr)
        {
            int userid = Convert.ToInt32(Request.Cookies["_xid"].Value.ToString());
               partnerviewmodal _model = new partnerviewmodal();
            partnerService _services = new partnerService();
            prjmanagerservices _ser = new prjmanagerservices(); 
            _model.partnerid = prjectmgr.partnerid;
            Session["partnerid"] = prjectmgr.partnerid;
            var message = _ser.add_new_partner_manager(prjectmgr, userid);
            _model.partners = _services.get_all_active_partners_byid(prjectmgr.partnerid); 
            _model = new helper().GenerateError<partnerviewmodal>(_model, message);
            _model.PERMISSIONS = _permission;
            return View("view", _model);
        }
        public ActionResult add_manager()
        {
            if (!_permission.Contains(5102))
            {
                return View("unauth");
            }
            prjmngr_item prjectmgr = new prjmngr_item();
                 partnerviewmodal _model = new partnerviewmodal();
            partnerService _services = new partnerService(); 
            prjectmgr.partnerid = Session["partnerid"] == null ? 0 : Convert.ToInt32(Session["partnerid"]);
            if (Session["clinetid"] == null)
            {
                return RedirectToAction("Index");
            }
            _model.partnerid = prjectmgr.partnerid; 
            _model.partners = _services.get_all_active_partners_byid(prjectmgr.clientid);
            _model.PERMISSIONS = _permission;
            return View("view", _model);
        }
        [HttpPost]
        public ActionResult update_manager(prjmngr_item prjectmgr)
        { 
              partnerviewmodal _model = new partnerviewmodal();
            partnerService _services = new partnerService();
            prjmanagerservices _ser = new prjmanagerservices();
            _model.partnerid = prjectmgr.partnerid;
            Session["partnerid"] = prjectmgr.partnerid;
            var message = _ser.update__partner_manager(prjectmgr);
            _model.partners = _services.get_all_active_partners_byid(prjectmgr.partnerid);
            _model = new helper().GenerateError<partnerviewmodal>(_model, message);
            _model.PERMISSIONS = _permission;
            return View("view", _model);
        }
        public ActionResult update_manager()
        {
            prjmngr_item prjectmgr = new prjmngr_item(); 
             partnerviewmodal _model = new partnerviewmodal();
            partnerService _services = new partnerService();
            prjmanagerservices _ser = new prjmanagerservices();
            _model.partnerid = Session["partnerid"] == null ? 0 : Convert.ToInt32(Session["partnerid"]);
            if (Session["clinetid"] == null)
            {
                return RedirectToAction("Index");
            }     _model.partners = _services.get_all_active_partners_byid(prjectmgr.partnerid);
            _model.PERMISSIONS = _permission;
            return View("view", _model);
        }
        public ActionResult delete_manager(string clienttoken, string token)
        {
            if (!_permission.Contains(5101))
            {
                return View("unauth");
            }
            Crypto _crypt = new Crypto();
            int id = Convert.ToInt32(_crypt.DecryptStringAES(token));
            int partnerid = Convert.ToInt32(_crypt.DecryptStringAES(clienttoken));
            partnerviewmodal _model = new partnerviewmodal();
            partnerService _services = new partnerService();
            prjmanagerservices _ser = new prjmanagerservices();
            _model.partnerid = partnerid;
             var message = _ser.delete_partner_manager(id);
            _model.partners = _services.get_all_active_partners_byid(partnerid);
            _model = new helper().GenerateError<partnerviewmodal>(_model, message);
            _model.PERMISSIONS = _permission;
            return View("view", _model);
        }
        [HttpPost]
        public ActionResult update(partnermodal_item _item)
        {

Views/partners/Index.cshtml
@{
    ViewBag.Title = "Partners";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var permission = Model.PERMISSIONS;
}
<link href="@Url.Content("~/Content/partners/index.min.css?v=1.0")" rel="stylesheet" />
@model hrm.Models.partnermodal
<div class="p-10">
</div>
<div class="p-30 p-t-none p-b-none">
    @if (!string.IsNullOrEmpty(Model.error_text))
    {
        <span id="alert" style="display:none;" data-class="@Model.alertclass" data-text="@Model.error_text"></span>
    }
    <div class="box mainbox" style="display: none;" id="uploadslide">
        @using (Html.BeginForm("partner", "import", FormMethod.Post, new { @id = "frmsendsms", @enctype = "multipart/form-data" }))
        {
            <div class="box-inner">
                <div class="col-md-12">
                    <h3 class="pull-left panel-title" style="padding-left: 0px !important;    padding-top: 10px;">Upload Partners</h3>
                    <button type="button" class="close closebox" aria-label="Close" autocomplete="random"><span aria-hidden="true">×</span></button>
                </div>
                <div class="clearfix"></div>
                <hr class="mt9" />
                <div class="clearfix"></div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label style="width:100%" class="notcapital">Upload a csv formatted file</label>
                        <div class="input-group input-group-file">
                            <span class="input-group-btn">
                                <span class="btn btn-primary btn-file">
                                    Browse <input required type="file" id="files" accept=".csv" class="form-control" name="file">
                                </span>
                            </span>
                            <input type="text" class="form-control" readonly="">
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label class="notcapital" style="width:100%">Download template</label>
                        <a href="@Url.Content("~/csvfiles/Partners.csv")" download="">  <img src="@Url.Content("~/Content/Images/csv.webp")" style="width:100px;" /></a>
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="col-md-12" style="position:relative;margin-top:20%;">
                </div>
                <div class="clearfix"></div>
                <hr />
                <div class="clearfix"></div>
                <div class="col-md-12">
                    <button type="submit" id="submit-file" class="btn btn-success"><i class="fas fa-cloud-upload-alt"></i> Import</button>
                </div>
            </div>
        }
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel">
                <div class="panel-heading">
                    <div class="col-md-6 col-sm-6">
                        <h3 class="panel-title" style="padding-left:7px;">
                           Partners
                        </h3>
                    </div>
                    <div class="col-md-6 col-sm-6 topbuttondiv">
                        <a class="btn btn-success btn-sm pull-right" href="@Url.Action("add", "partners")">
                            <i class="fa fa-plus"></i> Add partner
                        </a>
                        @if (permission.Contains(5094))
                        {
                            <a class="btn btn-success btn-sm pull-right m-r-8" onclick="Uploadfile()" href="#">
                                <i class="fas fa-cloud-upload-alt"></i> Upload
                            </a>
                        } 
                    </div>
                </div>
                <div class="panel-body p-none">
                    <div class="table-ultra-responsive custompadding-table">
                        <table class="table table-condensed nowrap data-table table-hover dataTable no-footer" id="table">
                            <thead>
                                <tr role="row">
                                    <th>Name</th>
                                    <th>Primary contact</th>
                                    <th>Rate</th>
                                    <th>Email</th>
                                    <th>Phone</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
<script>
    var pageSize = 25;
    var otable;
    var viewpermission = '@permission.Contains(5097).ToString().ToUpper()';
    var editpermission = '@permission.Contains(5096).ToString().ToUpper()';
    var deletepermission = '@permission.Contains(5098).ToString().ToUpper()';

</script>
<script src="@Url.Content("~/Content/partners/index.min.js?v=1.3")"></script>

Views/partners/view.cshtml
@{
    ViewBag.Title = @Model.partners.name;
    Layout = "~/Views/Shared/_Layout.cshtml";
    var permission = Model.PERMISSIONS;
 
}
@model hrm.Models.partnerviewmodal
<link href="@Url.Content("~/Content/partners/view_style.min.css?v=1.3")" rel="stylesheet" />
<div class="p-head-4">
</div> 
<div class="p-30 p-t-none p-b-none">
    @if (!string.IsNullOrEmpty(Model.error_text))
    {
        <span id="alert" style="display:none;" data-class="@Model.alertclass" data-text="@Model.error_text"></span>
    }
    <div class="box mainbox" style="display: none;" id="uploadslide">
        @using (Html.BeginForm("pmanager", "import", FormMethod.Post, new { @id = "pmanagerImport", @enctype = "multipart/form-data" }))
        {
            <div class="box-inner">
                <div class="col-md-12">
                    <h3 class="pull-left panel-title" style="padding-left: 0px !important;    padding-top: 10px;">Upload project manager</h3>
                    <button type="button" class="close closebox" aria-label="Close" autocomplete="random"><span aria-hidden="true">×</span></button>
                </div>
                <div class="clearfix"></div>
                <hr class="mt9" />
                <div class="clearfix"></div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label class="notcapital wdth100">Upload a csv formatted file </label>
                        <div class="input-group input-group-file">
                            <span class="input-group-btn">
                                <span class="btn btn-primary btn-file">
                                    Browse <input required type="file" id="files" accept=".csv" class="form-control" name="file">
                                </span>
                            </span>
                            <input type="text" class="form-control" readonly="">
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label class="notcapital" style="width:100%">Download template </label>
                        <a href="@Url.Content("~/csvfiles/manager.csv")" download="">  <img src="@Url.Content("~/Content/Images/csv.webp?v=1.2")" class="wdth100" /></a>
                        <input type="hidden" value="@Model.partnerid" name="partnerid" />
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="col-md-12" style="position:relative;margin-top:20%;">
                </div>
                <div class="clearfix"></div>
                <hr />
                <div class="clearfix"></div>
                <div class="col-md-12">
                    <button type="submit" id="submit-file" class="btn btn-success"><i class="fas fa-cloud-upload-alt"></i> Import</button>
                </div>
            </div>
        }
    </div>
    <div class="modal fade" id="add-new-manager" data-keyboard="false" data-backdrop="static" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                    <h4 class="modal-title" id="myModalLabel">Add new manager</h4>
                </div>
                @using (Html.BeginForm("add_manager", "partners", FormMethod.Post, new { @class = "form-some-up", @id = "addmgrfrm" }))
                {<div class="modal-body">
                        <div class="form-group">
                            <label>Name</label>
                            <input type="text" name="name" class="form-control capitalize" required />
                            <input type="hidden" name="partnerid" id="partnerid" />
                        </div>
                        <div class="form-group">
                            <label>Email</label>
                            <input type="email" name="email" class="form-control" />
                        </div>
                        <div class="form-group">
                            <label>Phone</label>
                            <input type="text" maxlength="12" name="phone" class="form-control phonenumber" />
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-success"><i class="fa fa-save"></i> Save</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fas fa-times-circle"></i> Close</button>
                    </div>
                }
            </div>
        </div>
    </div>
    <div class="modal fade" id="update-manager" data-keyboard="false" data-backdrop="static" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                    <h4 class="modal-title" id="myModalLabel">Edit manager</h4>
                </div>
                @using (Html.BeginForm("update_manager", "partners", FormMethod.Post, new { @class = "form-some-up", @id = "updtmgrfrm" }))
                {<div class="modal-body">
                        <div class="form-group">
                            <label>Name</label>
                            <input type="text" id="name" name="name" class="form-control capitalize" required />
                            <input type="hidden" name="prjmanagerid" id="prjmanagerid" />
                            <input type="hidden" name="partnerid" value="@Model.partnerid" />
                        </div>
                        <div class="form-group">
                            <label>Email</label>
                            <input type="email" name="email" id="email" class="form-control" />
                        </div>
                        <div class="form-group">
                            <label>Phone</label>
                            <input type="text" maxlength="12" name="phone" id="phone" class="form-control phonenumber" />
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-success"><i class="fa fa-save"></i> Update</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fas fa-times-circle"></i> Close</button>
                    </div>
                }
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
            <div class="panel">
                <div class="panel-heading formpanel-heading">
                    <div class="col-md-6 col-sm-6">
                        <h3 class="panel-title" style="padding-left: 5px">
                            Partner detail 
                        </h3>
                    </div>
                    <div class="col-md-6 col-sm-6 topbuttondiv">
                        <a class="btn btn-success btn-sm pull-right" href="@Url.Action("index","Partners",new { v=1234})">
                            <i class="fa fa-arrow-left"></i> Partner list
                        </a>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <label>Name:</label>
                        <span>@Model.partners.name</span>
                    </div>
                    <div class="form-group">
                        <label>Primary contact:</label>
                        <span>@Model.partners.primarycontactname</span>
                    </div>
                    <div class="form-group">
                        <label>Partner rate:</label>
                        <span>@Model.partners.rate</span>
                    </div>
                    <div class="form-group">
                        <label>Email:</label>
                        <span>@Model.partners.email</span>
                    </div>
                    <div class="form-group">
                        <label>Phone:</label>
                        <span>@Model.partners.phone</span>
                    </div>
                    <div class="form-group">
                        <label>Address:</label>
                        <span>@Model.partners.MapValidateAddress</span>
                    </div>
                    <div class="form-group">
                        <label>Suite / Apt. #:</label>
                        <span>@Model.partners.suite</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
            <div class="panel">
                <div class="panel-heading formpanel-heading">
                    <div class="col-md-6 col-sm-6 ">
                        <h3 class="panel-title pd-21 ">
                            Project manager
                        </h3>
                    </div>
                    <div class="col-md-6 col-sm-6 topbuttondiv mr-15-btn">
                        @if (permission.Contains(5102))
                        {
                            <a class="btn btn-success btn-sm pull-right" href="#" data-backdrop="static" onclick="add_new('@Model.partnerid')">
                                <i class="fa fa-plus"></i> Add new manager
                            </a>
                        } 
                        @if (permission.Contains(5099))
                        {
                            <a href="#" class="btn btn-success btn-sm pull-right" style="margin-right:8px;" data-backdrop="static" onclick="Uploadfile()">
                                <i class="fas fa-cloud-upload-alt"></i> Upload
                            </a>
                        } 
                    </div>
                </div>
                <div class="panel-body p-none">
                    <div class="col-md-12">
                        <div class="table-ultra-responsive responsivecustom">

                            <table class="table table-condensed nowrap data-table table-hover dataTable no-footer" id="table">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Phone</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    var pageSize = 25;
    var otable;
   var editpermission = '@permission.Contains(5100).ToString().ToUpper()';
    var deletepermission = '@permission.Contains(5101).ToString().ToUpper()';
    var _ajaxUrl = "@Url.Action("Fetchmanagers", "partners",new {partnerid= Model.partnerid })";
   
</script><script src="@Url.Content("~/Content/partners/view.min.js?v=1.2")"></script>